# 2시간(7,200,000), 1일(86,400,000) jwt token
token:
  expiration_time: 7200000
  refresh_time: 86400000
  secret: 'token_secret'
  public: MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAp+bUeq0y/QMQcjJM5zpa+x3M4liR24q29UWtJ8+Lm64m75XmMP1MTSfSMIkyAjf1Ieky/dXCCmXcXKyie7sVRh3dB1UAToIdG0DO8p0F1lEWwYMO385W5X8k3qXQUncSorpr3iTA7ku2uV25LfRlDhLZMLNcbZ1cGJ2lx04KFPGRuRUcsedLxJPPa9fgUoVSXRDGYhLtCrQ5h9ktxNedIk2TdJugGD/qYdiXy6dTwdul3ytNphB+n3CI6k6jfeJIDGRPsXQtuebP/WQETu7Q4IuDSNPc1b7FUSNwnNeM/LhPiniQw1/GqtW9ZyyZF1FEkBj1PILnde+5kP6V2h+n5zezrcNZhaPByTo+9JIgQssbfurerhBuVaY6YGqNA9aWxVX9yJ9AhyYZufOCZo+GyRAuRShvbzIyeL5O/KobIheZTriSR//nUXX78wmk1QD64AgDJVaoUQE75DZqdxQUog1i0zvWfdtDlLOKb2SaK80UV99bVeGmoQnXXUruZ4eNAgMBAAE=

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # random port 사용시 eureka server에 인스턴스가 각각 표시되지 않는다
    preferIpAddress: true # 서비스간 통신 시 hostname 보다 ip 를 우선
  client:
    register-with-eureka: true # eureka 서버에 등록
    fetch-registry: true # 외부 검색 가능
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka

# file attach location - messages{lang}.properties 도 이 경로에 위치한다.
file:
  directory: ${app.home:${user.home}}/msa-attach-volume # url 사용시에는 사용되지 않는다
  url: http://${file.hostname:localhost}:8080 # nginx 로 파일 다운로드 처리
messages:
  directory: ${file.directory}/messages

apigateway:
  host: http://localhost:8000

# rabbitmq server
#spring:
#  rabbitmq:
#    host: ${rabbitmq.hostname:localhost}
#    port: 5672
#    username: guest
#    password: guest
#  zipkin:
#    base-url: http://${zipkin.hostname:localhost}:${zipkin.port:9411}

egov:
  message: hello
