# 2시간(7,200,000), 1일(86,400,000) jwt token
token:
  expiration_time: 7200000
  refresh_time: 86400000
  secret: 'token_secret'
  public: MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAojbUV7N5EBivQEQoqRt16JhKdVZxsTtRjj7nw5RsyD+TBoUxdMyOTq6aIUrNS6ncCqGDTLEbbYqavyjlk6A0jqWViaEjp2EabigyZXXCr28xh90VCE4kbLvtP9mqtLWWJAtG0kN8YyY2i4a8ZHlCDmVT3ZgxaHQhaz1jroBc1RA8EReYzLOt2BHXakdkzMMkgEy3IH/2gw8J9ks+/kh71FhR9MzL+ZSK/DU7oNmvTwLGUSAaTfCuHxqMNhyz3wRmegPP2EObV9opDURscE7mls7UR8koMv0nkXbKQKsxD2npPoD9HBh5AoZh5ocsvNdO1OXMSNs2Ii1pgGc24rjZXxyisYBkV4wpvHLoawS7SrRsmYwy6UjdW9d789fx8ZuRiAxiCqq5pZdECca66Cad7t+hIwtVvTcJAVNWgvUujXBZABKtzaOATZk0sSduSgFXpB9HxARBSIc2c4uePueBnlPe/29a5PkFo6dUHsaACIFjduoYVYfR+3RNbKWm9Rw5AgMBAAE=
# 원본 키
#public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2Gh8nwgA/VjiTSDp96a0ztrHVBnrUhy6/pBO1RtdONcivm4dojpKGzDOaf/4GeupfOk+BaSYW2ow5qizMYia825TSwwk0/AQ04ShUtVbJ+45VsKV0/ARWtiK0zo1nz2zF6NBkFs1VzurkQBtOYM8wtErZF/lknRCUBP+tl4GrMdcaZ0Dza1u4JHR/Et3Z3P8Ocjkywf60Y6z5YuAbYWMs+4KfEsohIwDcnKnek01gNEwjF6HFWJ6fNmLFYCqNZhWYaH6g+QzAkMB4uir+j3AiqU3UyBdXnQ/0cSS6kptUaOXSfXVR1rmXeziU6eePLZ9hQF4l9/mkrsKD0vq936b0wIDAQAB

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # random port 사용시 eureka server에 인스턴스가 각각 표시되지 않는다
    preferIpAddress: true # 서비스간 통신 시 hostname 보다 ip 를 우선
  client:
    register-with-eureka: true # eureka 서버에 등록
    fetch-registry: true # 외부 검색 가능
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka

# file attach location - messages{lang}.properties 도 이 경로에 위치한다.
file:
  directory: ${app.home:${user.home}}/msa-attach-volume # url 사용시에는 사용되지 않는다
  url: http://${file.hostname:localhost}:8080 # nginx 로 파일 다운로드 처리
messages:
  directory: ${file.directory}/messages

apigateway:
  host: http://localhost:8000

# rabbitmq server
#spring:
#  rabbitmq:
#    host: ${rabbitmq.hostname:localhost}
#    port: 5672
#    username: guest
#    password: guest
#  zipkin:
#    base-url: http://${zipkin.hostname:localhost}:${zipkin.port:9411}

egov:
  message: hello
