spring:
  datasource:
    # Postgres 서버 타임존을 서울(KST)로 맞추기 위해 옵션 추가
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=public&options=-c%20TimeZone=Asia/Seoul}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:parkjinwoo}
    password: ${DB_PASSWORD:}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  batch:
    jdbc:
      initialize-schema: never
api:
  v1: /api/v1
