apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
spec:
#  쿠버네티스를 설정
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: apigateway
  ports:
    - name: http
      port: 8000
#      외부 포트 의미
      targetPort: 8000
-----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apigateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apigateway
    spec:
      containers:
        - name: apigateway
#          버전 의미
          image: apigateway:1.0.0
#          이미지가 존재할 때만 진행할 것
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service.default.svc.cluster.local:8888
          command: ["java"]
          args:
            - "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}"
            - "-Dlogstash.url=${LOGSTASH_URL}"
            - "-jar"
            - "/usr/app/apigateway.jar"
          ports:
#           k8s 완전 외부가 아닌 외부 포트
            - containerPort: 8000
          readinessProbe:
            httpGet:
#              해당 /actuator/health로 헬스 체크해서 주기적으로 서버가 살아 있는지 확인
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 20
#            경로에 있는 데이트를 컨테이너에 마운트 하겠다.
          volumeMounts:
            - name: messages
              mountPath: /usr/app/msa-attach-volume/messages
      volumes:
        - name: messages
          emptyDir: {}
